BEGIN;

-- Suppression des tables si elles existent déjà
DROP TABLE IF EXISTS "user", "prediction", "match", "play", "team", "own", "competition";

-- Création des tables dans le bon ordre
CREATE TABLE "competition" (
    "competition_id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "season" VARCHAR(255) NOT NULL,
    "logo" TEXT
);

CREATE TABLE "team" (
    "team_id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "country" VARCHAR(255) NOT NULL,
    "city" VARCHAR(255) NOT NULL,
    "logo" TEXT
);

CREATE TABLE "match" (
    "match_id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "competition_id" INTEGER NOT NULL,
    "date" TIMESTAMPTZ NOT NULL,
    "stadium" VARCHAR(255) NOT NULL,
    "score_home" INTEGER NOT NULL,
    "score_away" INTEGER NOT NULL,
    "outcome" VARCHAR(50) NOT NULL,
    FOREIGN KEY ("competition_id") REFERENCES "competition"("competition_id") ON DELETE CASCADE
);

CREATE TABLE "user" (
    "user_id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "first_name" VARCHAR(255) NOT NULL,
    "last_name" VARCHAR(255) NOT NULL,
    "pseudo" VARCHAR(255) UNIQUE NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "password" TEXT NOT NULL
);

CREATE TABLE "prediction" (
    "prediction_id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL,
    "match_id" INTEGER NOT NULL,
    "score_predi_home" INTEGER NOT NULL,
    "score_predi_away" INTEGER NOT NULL,
    "points_score" INTEGER NOT NULL,
    "points_outcome" INTEGER NOT NULL,
    FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE CASCADE,
    FOREIGN KEY ("match_id") REFERENCES "match"("match_id") ON DELETE CASCADE
);

CREATE TABLE "play" (
    "match_id" INTEGER NOT NULL,
    "team_id" INTEGER NOT NULL,
    "role" VARCHAR(50) NOT NULL,
    PRIMARY KEY ("match_id", "team_id"),
    FOREIGN KEY ("match_id") REFERENCES "match"("match_id") ON DELETE CASCADE,
    FOREIGN KEY ("team_id") REFERENCES "team"("team_id") ON DELETE CASCADE
);

CREATE TABLE "own" (
    "competition_id" INTEGER NOT NULL,
    "team_id" INTEGER NOT NULL,
    PRIMARY KEY ("competition_id", "team_id"),
    FOREIGN KEY ("competition_id") REFERENCES "competition"("competition_id") ON DELETE CASCADE,
    FOREIGN KEY ("team_id") REFERENCES "team"("team_id") ON DELETE CASCADE
);

COMMIT;